import React from 'react';
import { fmtMoneyCompact, ceoBusinessLineDisplayLabel } from '../../utils/formatters';
import { resolveColumnKey } from '../../utils/data.jsx';
import DrillModalContextBar from './DrillModalContextBar.jsx';

const WATERFALL_DRILL_CONTEXT =
  "Opportunities that roll into the CRO waterfall category you clicked. Amounts follow your waterfall / detail mapping; use this list to validate movement before/after the bar.";

export default function DrillDownModal({
  open,
  onClose,
  title,
  rows,
  total,
  config,
  /** CEO toggle: "All" | "New Business" | "Gross Expansion" */
  businessLine = 'All',
  contextHelper,
  definitionsSection = 'cro_waterfall',
  onOpenDefinitions,
}) {
  if (!open) return null;

  /**
   * Resolve the actual data keys based on the Sigma configuration.
   * This maps your internal config keys (e.g., wf_opp_name) to the 
   * unique column IDs generated by Sigma.
   */
  const keys = {
    name: resolveColumnKey(config?.wf_opp_name),
    owner: resolveColumnKey(config?.wf_opp_owner),
    bizLine: resolveColumnKey(config?.wf_business_line),
    recordType: resolveColumnKey(config?.wf_record_type),
    createdQtr: resolveColumnKey(config?.wf_created_qtr),
    amount: resolveColumnKey(config?.wf_amount)
  };

  return (
    <div style={styles.overlay}>
      <div style={styles.modal}>
        {/* Midnight Blue Header - Matches Horseman Design */}
        <div style={styles.header}>
          <div>
            <div style={styles.title}>{title}</div>
            <div style={styles.subtitle}>{rows.length} opportunities found</div>
          </div>
          <button onClick={onClose} style={styles.closeBtn}>✕</button>
        </div>

        <div style={{ padding: '0 18px 8px' }}>
          <DrillModalContextBar
            helperText={contextHelper ?? WATERFALL_DRILL_CONTEXT}
            definitionsSection={definitionsSection}
            onOpenDefinitions={onOpenDefinitions}
          />
        </div>

        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, padding: '0 18px 10px' }}>
          <div
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '7px 12px',
              borderRadius: 999,
              background: 'rgba(15,23,42,0.05)',
              border: '1px solid rgba(15,23,42,0.08)',
            }}
          >
            <span
              style={{
                fontSize: 11,
                fontWeight: 950,
                color: 'rgba(15,23,42,0.62)',
                textTransform: 'uppercase',
                letterSpacing: 0.3,
              }}
            >
              Business Line
            </span>
            <span style={{ fontSize: 12, fontWeight: 1000, color: 'rgba(15,23,42,0.92)', maxWidth: 300 }}>
              {ceoBusinessLineDisplayLabel(businessLine)}
            </span>
          </div>
        </div>
        
        <div style={styles.tableArea}>
          <table style={styles.table}>
            <thead>
              <tr style={styles.thRow}>
                <th style={styles.th}>Opportunity Name</th>
                <th style={styles.th}>Owner</th>
                <th style={styles.th}>Business Line</th>
                <th style={styles.th}>Record Type</th>
                <th style={styles.th}>Created Qtr</th>
                <th style={styles.th}>ARR (ACV)</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <tr key={i} style={i % 2 === 0 ? styles.trEven : styles.trOdd}>
                  <td style={styles.td}>{row[keys.name] || 'N/A'}</td>
                  <td style={styles.td}>{row[keys.owner] || 'N/A'}</td>
                  <td style={styles.td}>{row[keys.bizLine] || 'N/A'}</td>
                  <td style={styles.td}>{row[keys.recordType] || 'N/A'}</td>
                  <td style={styles.td}>{row[keys.createdQtr] || 'N/A'}</td>
                  <td style={styles.td}>
                    <span style={{ fontWeight: 950, color: '#0b3251' }}>
                      {fmtMoneyCompact(row[keys.amount] || 0)}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Green 100 Total Footer - Matches Horseman Design */}
        <div style={styles.footer}>
          <div style={styles.footerText}>GRAND TOTAL</div>
          <div style={styles.footerValue}>{fmtMoneyCompact(total)}</div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  overlay: { 
    position: 'fixed', 
    inset: 0, 
    backgroundColor: 'rgba(15,23,42,0.6)', 
    display: 'grid', 
    placeItems: 'center', 
    zIndex: 1000, 
    padding: 40 
  },
  modal: { 
    backgroundColor: 'white', 
    borderRadius: 12, 
    width: '95%', 
    maxWidth: '1500px', 
    maxHeight: '85vh', 
    display: 'flex', 
    flexDirection: 'column', 
    overflow: 'hidden', 
    boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)' 
  },
  header: { 
    padding: '16px 24px', 
    backgroundColor: '#0b3251', 
    color: 'white', 
    display: 'flex', 
    justifyContent: 'space-between', 
    alignItems: 'center' 
  },
  title: { 
    fontSize: 18, 
    fontWeight: 1000, 
    letterSpacing: '0.5px' 
  },
  subtitle: { 
    fontSize: 12, 
    opacity: 0.8, 
    fontWeight: 700 
  },
  closeBtn: { 
    background: 'none', 
    border: 'none', 
    color: 'white', 
    fontSize: 24, 
    cursor: 'pointer', 
    fontWeight: 900 
  },
  tableArea: { 
    flex: 1, 
    overflowY: 'auto', 
    padding: '0 12px' 
  },
  table: { 
    width: '100%', 
    borderCollapse: 'collapse' 
  },
  thRow: { 
    backgroundColor: '#334155', 
    borderBottom: '2px solid #e2e8f0', 
    position: 'sticky', 
    top: 0, 
    zIndex: 10 
  },
  th: { 
    padding: '14px 12px', 
    textAlign: 'left', 
    fontSize: 11, 
    fontWeight: 950, 
    textTransform: 'uppercase', 
    color: 'white' 
  },
  trEven: { 
    backgroundColor: '#f8fafc' 
  },
  trOdd: { 
    backgroundColor: '#ffffff' 
  },
  td: { 
    padding: '12px 12px', 
    fontSize: 13, 
    borderBottom: '1px solid #f1f5f9', 
    color: '#1e293b', 
    fontWeight: 800 
  },
  footer: { 
    padding: '14px 24px', 
    backgroundColor: '#0e9976', 
    color: 'white', 
    display: 'flex', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    fontWeight: 1000, 
    fontSize: 18 
  }
};